FROM golang:1.19

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
#　RUN go install github.com/swaggo/swag/cmd/swag@latest && swag init
# RUN go test
RUN go build -v -o /usr/local/bin/app 

# デバッグモード
CMD ["app","--debug","--reset"]
# release mode
# CMD ["app"]